#!/bin/bash

cd $HOME
mkdir apb
cd apb

echo "Start: Cloning PKGBUILDs ..."
git clone https://github.com/Barg-Project/PKGBUILD.git
echo "End: PKGBUILDs has ben Cloned."

echo "Start: Cloning BargOS pacman repository ..."
git clone https://github.com/Barg-Project/barg.git
echo "End: BargOS pacman repository has been Cloned."

pbd="$(pwd)/PKGBUILD"
pd="$(pwd)/barg"

cd $pbd
echo "Start: Preparing the list of packages to build ..."
exa -D --long --no-filesize --no-icons --no-permissions --no-time --no-user > pkg.list
echo "End: Packages to Build Listed."

i=0

echo "Start: Making packages ..."
while read line; do
    i=$(($i+1))
    cd $(echo "$line")
    makepkg -c -f -r -s --skippgpcheck
    mv *.pkg.tar.zst* $pd/x86_64/
    cd $pbd
done < pkg.list
echo "End: Packages were made."

cd $pd
echo "Start: Downloading README.md generator ..."
wget https://raw.githubusercontent.com/Barg-Project/autopkg/main/auto-gen.py
echo "End: README.md generator Downloaded."

echo "Start: Downloading repoadd script ..."
wget https://raw.githubusercontent.com/Barg-Project/autopkg/main/repoadd.sh
echo "End: repoadd script Downloaded."

echo "Start: Adding packages to repository ..."
bash ./repoadd.sh barg
echo "End: Packages were added to repository."

echo "Start: Generating README.md ..."
python ./auto-gen.py
echo "End: README.me Generated."

echo "Start: Cleaning ..."
rm -rf auto-gen.py repoadd.sh
echo "End: directory has been cleaned."

commit="$(date +%x)"
echo "Start: Adding, Commiting & Pushing ..."
git add -A
git commit -m $commit
git push -f
echo "End: Repository Pushed."

cd $pbd
echo "Start: Pushing Changes ..."
git add -A
git commit -m $commit
git push -f
echo "End: Changes Pushed."

